version: '3.8'

services:
  runtpl:
    build:
      context: ..
      dockerfile: runtpl/Dockerfile
    ports:
      - "19999:19999"
    volumes:
      - /var/snap/docker/common/var-lib-docker/volumes/kazu-cmd/_data/cmd/runtpl/tmpl:/app/tmpl
    environment:
      - LOG_LEVEL=info
    container_name: runtpl-server
    restart: unless-stopped
    networks:
      - runtpl-network

networks:
  runtpl-network:
    driver: bridge
